-- MySQL Script generated by MySQL Workbench
-- Thu May 23 14:47:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moto` DEFAULT CHARACTER SET utf8 ;
USE `moto` ;

-- -----------------------------------------------------
-- Table `moto`.`dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`dealer` (
  `id` BIGINT(20) NOT NULL COMMENT '经销商id',
  `number` VARCHAR(4) NULL DEFAULT NULL COMMENT '经销商编号',
  `name` VARCHAR(32) NULL DEFAULT NULL COMMENT '经销商名字',
  `is_deleted` TINYINT(4) NULL DEFAULT '1' COMMENT '是否可用，1/0，默认为1',
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `creator_id` BIGINT(20) NULL DEFAULT NULL,
  `creator_name` VARCHAR(32) NULL DEFAULT NULL,
  `creator_type` VARCHAR(16) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `updater_id` BIGINT(20) NULL DEFAULT NULL,
  `updater_name` VARCHAR(32) NULL DEFAULT NULL,
  `updater_type` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '经销商';


-- -----------------------------------------------------
-- Table `moto`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`device` (
  `id` BIGINT(20) NOT NULL COMMENT '设备id',
  `number` VARCHAR(32) NULL DEFAULT NULL COMMENT '设备编号',
  `card_number` VARCHAR(32) NULL DEFAULT NULL COMMENT '物联网卡号',
  `status` VARCHAR(12) NULL DEFAULT NULL COMMENT '状态',
  `is_deleted` TINYINT(4) NULL DEFAULT '1' COMMENT '是否可用，默认1',
  `created_at` DATETIME(6) NULL DEFAULT NULL COMMENT '创建时间',
  `creator_id` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人id',
  `creator_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '创建人姓名',
  `creator_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '创建人类型',
  `updated_at` DATETIME(6) NULL DEFAULT NULL COMMENT '最近更新时间',
  `updater_id` BIGINT(20) NULL DEFAULT NULL COMMENT '最近更新人id',
  `updater_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '最近更新人姓名',
  `updater_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '最近更新人类型',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '设备';


-- -----------------------------------------------------
-- Table `moto`.`device_assign_dealer_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`device_assign_dealer_log` (
  `id` BIGINT(20) NOT NULL,
  `dealer_id` BIGINT(20) NULL DEFAULT NULL COMMENT '经销商id',
  `dealer_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '经销商名字',
  `status` TINYINT(4) NULL DEFAULT '0' COMMENT '分配状态，0为失败/1为成功，默认为0',
  `device_list` TEXT NULL DEFAULT NULL COMMENT '分配设备列表信息，用”|”分割',
  `info` TEXT NULL DEFAULT NULL COMMENT '分配结果信息',
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `creator_id` BIGINT(20) NULL DEFAULT NULL,
  `creator_name` VARCHAR(16) NULL DEFAULT NULL,
  `creator_type` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '设备分配';

CREATE INDEX `fk_device_assign_dealer_log_dealer1_idx` ON `moto`.`device_assign_dealer_log` (`dealer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `moto`.`device_check_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`device_check_log` (
  `id` BIGINT(20) NOT NULL,
  `device_id` BIGINT(20) NULL DEFAULT NULL COMMENT '设备id',
  `device_number` VARCHAR(32) NULL DEFAULT NULL COMMENT '设备号',
  `status` VARCHAR(16) NULL DEFAULT NULL COMMENT '检测结果',
  `info` TEXT NULL DEFAULT NULL COMMENT '设备检测结果具体信息',
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `creator_id` BIGINT(20) NULL DEFAULT NULL,
  `creator_name` VARCHAR(16) NULL DEFAULT NULL,
  `creator_type` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_device_check_log_device1_idx` ON `moto`.`device_check_log` (`device_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `moto`.`factory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`factory` (
  `id` BIGINT(20) NOT NULL COMMENT '主机厂id',
  `number` VARCHAR(4) NULL DEFAULT NULL COMMENT '主机厂编号',
  `name` VARCHAR(32) NULL DEFAULT NULL COMMENT '主机厂名字',
  `code` VARCHAR(3) NULL DEFAULT NULL COMMENT '主机厂条形码编号',
  `is_deleted` TINYINT(4) NULL DEFAULT '1' COMMENT '是否可用，1/0，默认为1',
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `creator_id` BIGINT(20) NULL DEFAULT NULL,
  `creator_name` VARCHAR(32) NULL DEFAULT NULL,
  `creator_type` VARCHAR(16) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `updater_id` BIGINT(20) NULL DEFAULT NULL,
  `updater_name` VARCHAR(32) NULL DEFAULT NULL,
  `updater_type` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '主机厂';


-- -----------------------------------------------------
-- Table `moto`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`vehicle` (
  `id` BIGINT(20) NOT NULL,
  `vehicle_model_id` BIGINT(20) NULL DEFAULT NULL COMMENT '车型id',
  `vehicle_mode_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '车型名字',
  `vin` VARCHAR(32) NULL DEFAULT NULL COMMENT '车架号',
  `engine_number` VARCHAR(32) NULL DEFAULT NULL COMMENT '发动机号',
  `device_id` BIGINT(20) NULL DEFAULT NULL COMMENT '设备id',
  `device_numer` VARCHAR(32) NULL DEFAULT NULL COMMENT '设备号',
  `factory_id` BIGINT(20) NULL DEFAULT NULL COMMENT '主机厂id',
  `factory_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '主机厂名字',
  `device_number` VARCHAR(32) NULL DEFAULT NULL COMMENT '设备号',
  `dealer_id` BIGINT(20) NULL DEFAULT NULL COMMENT '经销商id',
  `dealer_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '经销商名字',
  `bind_mobile` VARCHAR(11) NULL DEFAULT NULL COMMENT '车辆绑定手机号',
  `color` VARCHAR(4) NULL DEFAULT NULL,
  `license_number` VARCHAR(10) NULL DEFAULT NULL COMMENT '车牌号',
  `product_at` DATETIME(6) NULL DEFAULT NULL,
  `status` VARCHAR(12) NULL DEFAULT NULL COMMENT '状态',
  `created_at` DATETIME(6) NULL DEFAULT NULL COMMENT '创建时间',
  `creator_id` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人id',
  `creator_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '创建人姓名',
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '更新时间',
  `updater_id` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人id',
  `updater_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '更新人姓名',
  `creator_type` VARCHAR(16) NULL DEFAULT NULL,
  `updater_type` VARCHAR(16) NULL DEFAULT NULL,
  `device_id1` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '车辆';

CREATE INDEX `fk_vehicle_vehicle_model1_idx` ON `moto`.`vehicle` (`vehicle_model_id` ASC) VISIBLE;

CREATE INDEX `fk_vehicle_factory1_idx` ON `moto`.`vehicle` (`factory_id` ASC) VISIBLE;

CREATE INDEX `fk_vehicle_dealer1_idx` ON `moto`.`vehicle` (`dealer_id` ASC) VISIBLE;

CREATE INDEX `fk_vehicle_device1_idx` ON `moto`.`vehicle` (`device_id` ASC) VISIBLE;

CREATE INDEX `fk_vehicle_device1_idx1` ON `moto`.`vehicle` (`device_id1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `moto`.`vehicle_assign_dealer_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`vehicle_assign_dealer_log` (
  `id` BIGINT(20) NOT NULL,
  `dealer_id` BIGINT(20) NULL DEFAULT NULL COMMENT '经销商id',
  `dealer_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '经销商名字',
  `status` TINYINT(4) NULL DEFAULT '0' COMMENT '分配状态，0为失败/1为成功，默认为0',
  `vehicle_list` TEXT NULL DEFAULT NULL COMMENT '分配车辆车架号列表信息，用”|”分割',
  `info` TEXT NULL DEFAULT NULL COMMENT '分配车辆结果信息',
  `created_at` DATETIME(6) NULL DEFAULT NULL COMMENT '创建时间',
  `creator_id` BIGINT(20) NULL DEFAULT NULL,
  `creator_name` VARCHAR(16) NULL DEFAULT NULL,
  `creator_type` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '车辆分配';

CREATE INDEX `fk_vehicle_assign_dealer_log_dealer1_idx` ON `moto`.`vehicle_assign_dealer_log` (`dealer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `moto`.`vehicle_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`vehicle_brand` (
  `id` BIGINT(20) NOT NULL,
  `bid` BINARY(4) NULL DEFAULT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `url` VARCHAR(256) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `creator_id` BIGINT(20) NULL DEFAULT NULL,
  `creator_name` VARCHAR(32) NULL DEFAULT NULL,
  `creator_type` VARCHAR(16) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updater_id` BIGINT(20) NULL DEFAULT NULL,
  `updater_name` VARCHAR(32) NULL DEFAULT NULL,
  `updater_type` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '品牌';


-- -----------------------------------------------------
-- Table `moto`.`vehicle_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto`.`vehicle_model` (
  `id` BIGINT(20) NOT NULL,
  `bid` BINARY(4) NULL DEFAULT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `brand_id` BIGINT(20) NULL DEFAULT NULL,
  `brand_name` VARCHAR(32) NULL DEFAULT NULL,
  `url` VARCHAR(256) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `creator_id` BIGINT(20) NULL DEFAULT NULL,
  `creator_name` VARCHAR(32) NULL DEFAULT NULL,
  `creator_type` VARCHAR(16) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updater_id` BIGINT(20) NULL DEFAULT NULL,
  `updater_name` VARCHAR(32) NULL DEFAULT NULL,
  `updater_type` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '车型';

CREATE INDEX `fk_vehicle_model_vehicle_brand_idx` ON `moto`.`vehicle_model` (`brand_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
