CREATE FUNCTION `ORDERED_UUID`(uuid VARCHAR(36)) RETURNS VARCHAR(32)
RETURN UPPER(CONCAT(SUBSTR(uuid, 15, 4), SUBSTR(uuid, 10, 4), SUBSTR(uuid, 1, 8), SUBSTR(uuid, 20, 4), SUBSTR(uuid, 25)));

CREATE FUNCTION `RANDOM_UUID`() RETURNS VARCHAR(32)
RETURN UPPER(REPLACE(UUID(), '-', ''));
