spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:44444/moto?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    serialization:
      write_dates_as_timestamps: true
mybatis:
  mapper-locations: classpath*:com/sodacar/deer/dao/mapper/xml/*Mapper.xml
  type-aliases-package: com.sodacar.deer.dao.model
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
default:
  exception:
    code: too_busy